//! Browser/palette catalog: ~786 Simulink-inspired block definitions.
//!
//! Auto-generated from the legacy editor block browser and folded into the
//! unified catalog so the editor palette and the renderer share one source.
//! These are metadata-only entries (shape, ports, category, description); the
//! richer hand-written `core`/`dashboard` libraries and the bridged virtual
//! libraries take precedence on key collisions, contributing icons and
//! renderers.  Add your own blocks here or in a new sibling file.

#![cfg(feature = "egui")]

use crate::simulink_libraries::types::{IOPorts, SimulinkBlockDefinition};

const fn io(n: u32) -> IOPorts {
    if n == 0 {
        IOPorts::None
    } else {
        IOPorts::Fixed(n)
    }
}

const fn e(
    block_type: &'static str,
    category: &'static str,
    display_name: &'static str,
    inputs: u32,
    outputs: u32,
    description: &'static str,
) -> SimulinkBlockDefinition {
    SimulinkBlockDefinition::new(block_type, category)
        .with_display_name(display_name)
        .with_ports(io(inputs), io(outputs))
        .with_description(description)
}

#[rustfmt::skip]
pub static BLOCKS: &[SimulinkBlockDefinition] = &[
    // ──── Sources ────
    e("Constant", "Sources", "Constant", 0, 1, "Output a constant value"),
    e("Ground", "Sources", "Ground", 0, 1, "Ground (zero) signal source"),
    e("Inport", "Sources", "Inport", 0, 1, "External input port"),
    e("FromWorkspace", "Sources", "From Workspace", 0, 1, "Load data from workspace variable"),
    e("FromFile", "Sources", "From File", 0, 1, "Read data from MAT file"),
    e("Clock", "Sources", "Clock", 0, 1, "Output simulation time"),
    e("DigitalClock", "Sources", "Digital Clock", 0, 1, "Output simulation time at specified rate"),
    e("Step", "Sources", "Step", 0, 1, "Step function input"),
    e("Ramp", "Sources", "Ramp", 0, 1, "Ramp function input"),
    e("SineWave", "Sources", "Sine Wave", 0, 1, "Generate sine wave signal"),
    e("SignalGenerator", "Sources", "Signal Generator", 0, 1, "Generate various waveforms"),
    e("Pulse", "Sources", "Pulse Generator", 0, 1, "Generate square pulse signal"),
    e("Chirp", "Sources", "Chirp Signal", 0, 1, "Generate frequency-swept signal"),
    e("RandomNumber", "Sources", "Random Number", 0, 1, "Generate random number using normal distribution"),
    e("UniformRandom", "Sources", "Uniform Random Number", 0, 1, "Generate uniformly distributed random numbers"),
    e("BandLimitedWhiteNoise", "Sources", "Band-Limited White Noise", 0, 1, "White noise with specified bandwidth"),
    e("Repeating", "Sources", "Repeating Sequence", 0, 1, "Generate repeating arbitrary signal"),
    e("RepeatingStair", "Sources", "Repeating Sequence Stair", 0, 1, "Generate repeating staircase signal"),
    e("RepeatingInterp", "Sources", "Repeating Sequence Interpolated", 0, 1, "Repeating sequence with interpolation"),
    e("Counter", "Sources", "Counter Free-Running", 0, 1, "Free running counter output"),
    e("CounterLimited", "Sources", "Counter Limited", 0, 1, "Counter with configurable limit"),
    e("EnumConstant", "Sources", "Enumerated Constant", 0, 1, "Output enumerated type constant"),
    e("TimeTableLookup", "Sources", "Time Table Lookup", 0, 1, "Table-based time signal"),
    e("SignalBuilderBlock", "Sources", "Signal Builder", 0, 1, "Build signals interactively"),
    e("WaveformGenerator", "Sources", "Waveform Generator", 0, 1, "Generate standard waveforms"),
    e("MultiPortSwGen", "Sources", "Multi-port Waveform Generator", 0, 1, "Multi-output waveform gen"),
    e("Playback", "Sources", "Playback", 0, 1, "Play back recorded signal"),
    // ──── Sinks ────
    e("Outport", "Sinks", "Outport", 1, 0, "External output port"),
    e("Terminator", "Sinks", "Terminator", 1, 0, "Terminate unconnected signal"),
    e("Scope", "Sinks", "Scope", 1, 0, "Display signal in scope window"),
    e("FloatingScope", "Sinks", "Floating Scope", 0, 0, "Free-floating scope"),
    e("Display", "Sinks", "Display", 1, 0, "Show signal value numerically"),
    e("ToWorkspace", "Sinks", "To Workspace", 1, 0, "Write data to workspace variable"),
    e("ToFile", "Sinks", "To File", 1, 0, "Write data to MAT file"),
    e("XYGraph", "Sinks", "XY Graph", 2, 0, "Display XY plot of two signals"),
    e("Stop", "Sinks", "Stop Simulation", 1, 0, "Stop simulation when input is nonzero"),
    e("OutBus", "Sinks", "Out Bus Element", 1, 0, "Output bus element"),
    e("Record", "Sinks", "Record", 1, 0, "Record signal data"),
    // ──── Math Operations ────
    e("Sum", "Math Operations", "Sum / Add", 2, 1, "Add or subtract inputs"),
    e("Add", "Math Operations", "Add", 2, 1, "Add inputs"),
    e("Subtract", "Math Operations", "Subtract", 2, 1, "Subtract inputs"),
    e("Product", "Math Operations", "Product", 2, 1, "Multiply or divide inputs"),
    e("Gain", "Math Operations", "Gain", 1, 1, "Multiply input by constant gain"),
    e("Abs", "Math Operations", "Abs", 1, 1, "Absolute value"),
    e("Sign", "Math Operations", "Sign", 1, 1, "Signum function"),
    e("Sqrt", "Math Operations", "Sqrt", 1, 1, "Square root"),
    e("ReciprocalSqrt", "Math Operations", "Reciprocal Sqrt", 1, 1, "Reciprocal square root (1/sqrt)"),
    e("MathFunction", "Math Operations", "Math Function", 1, 1, "Common math function (exp, log, pow, etc.)"),
    e("TrigFunction", "Math Operations", "Trigonometric Function", 1, 1, "Trig functions (sin, cos, tan, etc.)"),
    e("MinMax", "Math Operations", "MinMax", 2, 1, "Minimum or maximum of inputs"),
    e("DotProduct", "Math Operations", "Dot Product", 2, 1, "Vector dot product"),
    e("CrossProduct", "Math Operations", "Cross Product", 2, 1, "Vector cross product"),
    e("Divide", "Math Operations", "Divide", 2, 1, "Element-wise division"),
    e("Mod", "Math Operations", "Mod (Remainder)", 2, 1, "Modulus / remainder"),
    e("Round", "Math Operations", "Rounding Function", 1, 1, "Round, floor, ceil, fix"),
    e("Bias", "Math Operations", "Bias", 1, 1, "Add bias value to input"),
    e("SliderGain", "Math Operations", "Slider Gain", 1, 1, "Variable gain via slider"),
    e("Polynomial", "Math Operations", "Polynomial", 1, 1, "Evaluate polynomial coefficients"),
    e("Magnitude-AngleToComplex", "Math Operations", "Magnitude-Angle to Complex", 2, 1, "Convert magnitude and angle to complex"),
    e("RealImagToComplex", "Math Operations", "Real-Imag to Complex", 2, 1, "Convert real and imag to complex"),
    e("ComplexToMagnitudeAngle", "Math Operations", "Complex to Magnitude-Angle", 1, 2, "Extract magnitude and angle from complex"),
    e("ComplexToRealImag", "Math Operations", "Complex to Real-Imag", 1, 2, "Extract real and imag from complex"),
    e("Reshape", "Math Operations", "Reshape", 1, 1, "Reshape signal dimensions"),
    e("WeightedSum", "Math Operations", "Weighted Sum", 2, 1, "Weighted sum of inputs"),
    e("SumOfElements", "Math Operations", "Sum of Elements", 1, 1, "Sum all elements of vector/matrix"),
    e("ProductOfElements", "Math Operations", "Product of Elements", 1, 1, "Product of all elements"),
    e("Norm", "Math Operations", "Vector Norm", 1, 1, "Compute vector norm"),
    e("Unary Minus", "Math Operations", "Unary Minus", 1, 1, "Negate signal"),
    e("Power", "Math Operations", "Power", 2, 1, "Raise to power"),
    e("Exponential", "Math Operations", "Exponential", 1, 1, "e^x"),
    e("NaturalLog", "Math Operations", "Natural Log", 1, 1, "ln(x)"),
    e("Log10", "Math Operations", "Log10", 1, 1, "log10(x)"),
    e("Log2", "Math Operations", "Log2", 1, 1, "log2(x)"),
    e("Hypot", "Math Operations", "Hypot", 2, 1, "Hypotenuse sqrt(x^2+y^2)"),
    e("MaxConstraint", "Math Operations", "Max Constraint", 2, 1, "Output max of inputs with constraint"),
    e("MinConstraint", "Math Operations", "Min Constraint", 2, 1, "Output min of inputs with constraint"),
    // ──── Logic and Bit Operations ────
    e("Logic", "Logic and Bit Operations", "Logical Operator", 2, 1, "AND, OR, NAND, NOR, XOR, NOT"),
    e("RelationalOperator", "Logic and Bit Operations", "Relational Operator", 2, 1, "Compare: ==, ~=, <, <=, >, >="),
    e("Relational Operator", "Logic and Bit Operations", "Relational Operator", 2, 1, "Compare: ==, ~=, <, <=, >, >= (simulink/Logic and Bit Operations)"),
    e("Compare", "Logic and Bit Operations", "Compare To Zero", 1, 1, "Compare signal to zero"),
    e("CompareToConstant", "Logic and Bit Operations", "Compare To Constant", 1, 1, "Compare signal to constant"),
    e("Compare To Constant", "Logic and Bit Operations", "Compare To Constant", 1, 1, "Compare signal to constant (simulink/Logic and Bit Operations)"),
    e("BitwiseOperator", "Logic and Bit Operations", "Bitwise Operator", 1, 1, "AND, OR, XOR, NOT on bits"),
    e("ShiftArithmetic", "Logic and Bit Operations", "Shift Arithmetic", 1, 1, "Bitwise arithmetic shift"),
    e("BitClear", "Logic and Bit Operations", "Bit Clear", 1, 1, "Clear specified bit"),
    e("BitSet", "Logic and Bit Operations", "Bit Set", 1, 1, "Set specified bit"),
    e("ExtractBits", "Logic and Bit Operations", "Extract Bits", 1, 1, "Extract range of bits"),
    e("IntervalTest", "Logic and Bit Operations", "Interval Test", 1, 1, "Test if value is in interval"),
    e("IntervalTestDynamic", "Logic and Bit Operations", "Interval Test Dynamic", 3, 1, "Dynamic interval test"),
    e("CombLogic", "Logic and Bit Operations", "Combinatorial Logic", 1, 1, "Truth-table based logic"),
    e("Detect", "Logic and Bit Operations", "Detect Change", 1, 1, "Detect when signal changes"),
    e("Detect Change", "Logic and Bit Operations", "Detect Change", 1, 1, "Detect when signal changes (simulink/Logic and Bit Operations)"),
    e("DetectDecrease", "Logic and Bit Operations", "Detect Decrease", 1, 1, "Detect when signal decreases"),
    e("Detect Decrease", "Logic and Bit Operations", "Detect Decrease", 1, 1, "Detect when signal decreases (simulink/Logic and Bit Operations)"),
    e("DetectIncrease", "Logic and Bit Operations", "Detect Increase", 1, 1, "Detect when signal increases"),
    e("Detect Increase", "Logic and Bit Operations", "Detect Increase", 1, 1, "Detect when signal increases (simulink/Logic and Bit Operations)"),
    e("DetectRisePositive", "Logic and Bit Operations", "Detect Rise Positive", 1, 1, "Detect rising edge"),
    e("DetectRiseNonneg", "Logic and Bit Operations", "Detect Rise Nonnegative", 1, 1, "Detect nonnegative rising edge"),
    e("DetectFallNeg", "Logic and Bit Operations", "Detect Fall Negative", 1, 1, "Detect falling edge"),
    e("DetectFallNonpos", "Logic and Bit Operations", "Detect Fall Nonpositive", 1, 1, "Detect nonpositive falling"),
    // ──── Continuous ────
    e("Integrator", "Continuous", "Integrator", 1, 1, "Continuous-time integrator"),
    e("IntegratorLimited", "Continuous", "Integrator Limited", 1, 1, "Integrator with saturation limits"),
    e("IntegratorSecondOrder", "Continuous", "Integrator Second Order", 1, 2, "Second-order integrator (x, dx/dt)"),
    e("Derivative", "Continuous", "Derivative", 1, 1, "Time derivative du/dt"),
    e("TransferFcn", "Continuous", "Transfer Function", 1, 1, "Transfer function (s-domain)"),
    e("StateSpace", "Continuous", "State-Space", 1, 1, "State-space model (A,B,C,D)"),
    e("ZeroPole", "Continuous", "Zero-Pole", 1, 1, "Zero-pole-gain transfer function"),
    e("TransportDelay", "Continuous", "Transport Delay", 1, 1, "Fixed-time transport delay"),
    e("VariableTransportDelay", "Continuous", "Variable Transport Delay", 2, 1, "Variable time delay"),
    e("PadeApprox", "Continuous", "Pade Approximation", 1, 1, "Pade approximation of time delay"),
    e("PID", "Continuous", "PID Controller", 1, 1, "Continuous PID controller"),
    e("PIDAdvanced", "Continuous", "PID Controller (2DOF)", 2, 1, "Two-degree-of-freedom PID"),
    e("PIDDiscrete", "Continuous", "Discrete PID Controller", 1, 1, "Discrete-time PID controller"),
    e("PIDDiscreteAdvanced", "Continuous", "Discrete PID (2DOF)", 2, 1, "Discrete-time 2DOF PID"),
    e("Lead Lag", "Continuous", "Lead-Lag Compensator", 1, 1, "Lead-lag compensator"),
    // ──── Discrete ────
    e("UnitDelay", "Discrete", "Unit Delay", 1, 1, "Delay signal by one sample period"),
    e("Delay", "Discrete", "Delay", 1, 1, "Delay by N samples"),
    e("VariableIntegerDelay", "Discrete", "Variable Integer Delay", 2, 1, "Variable integer sample delay"),
    e("TappedDelay", "Discrete", "Tapped Delay", 1, 1, "Multi-tap delay line"),
    e("DiscreteIntegrator", "Discrete", "Discrete-Time Integrator", 1, 1, "Discrete integration / accumulator"),
    e("DiscreteDerivative", "Discrete", "Discrete Derivative", 1, 1, "Discrete-time derivative"),
    e("Discrete Derivative", "Discrete", "Discrete Derivative", 1, 1, "Discrete-time derivative (simulink/Discrete)"),
    e("DiscreteTransferFcn", "Discrete", "Discrete Transfer Fcn", 1, 1, "Discrete transfer function (z-domain)"),
    e("DiscreteZeroPole", "Discrete", "Discrete Zero-Pole", 1, 1, "Discrete zero-pole-gain"),
    e("DiscreteStateSpace", "Discrete", "Discrete State-Space", 1, 1, "Discrete state space model"),
    e("DiscreteFilter", "Discrete", "Discrete Filter", 1, 1, "IIR / FIR discrete filter"),
    e("DiscreteFIR", "Discrete", "Discrete FIR Filter", 1, 1, "Finite impulse response filter"),
    e("DiscreteIIR", "Discrete", "Discrete IIR Filter", 1, 1, "Infinite impulse response filter"),
    e("ZeroOrderHold", "Discrete", "Zero-Order Hold", 1, 1, "Zero-order hold (sample)"),
    e("FirstOrderHold", "Discrete", "First-Order Hold", 1, 1, "First-order hold interpolation"),
    e("RateTransition", "Discrete", "Rate Transition", 1, 1, "Handle multi-rate transitions"),
    e("Downsample", "Discrete", "Downsample", 1, 1, "Reduce sample rate by integer factor"),
    e("Upsample", "Discrete", "Upsample", 1, 1, "Increase sample rate by integer factor"),
    e("Memory", "Discrete", "Memory", 1, 1, "Output previous sample value"),
    e("ResettableDelay", "Discrete", "Resettable Delay", 2, 1, "Unit delay with external reset"),
    e("ZeroOrderHoldExact", "Discrete", "Zero-Order Hold (Exact)", 1, 1, "Exact ZOH"),
    e("DiscreteMedianFilter", "Discrete", "Discrete Median Filter", 1, 1, "Moving median filter"),
    e("DiscreteMovingAverage", "Discrete", "Moving Average", 1, 1, "Moving average filter"),
    e("DiscretePIDv2", "Discrete", "PID Controller v2", 1, 1, "Second-generation PID"),
    // ──── Signal Routing ────
    e("Mux", "Signal Routing", "Mux", 2, 1, "Multiplex scalar signals into vector"),
    e("Demux", "Signal Routing", "Demux", 1, 2, "Demultiplex vector into scalars"),
    e("Switch", "Signal Routing", "Switch", 3, 1, "Switch between two inputs based on threshold"),
    e("MultiPortSwitch", "Signal Routing", "Multiport Switch", 3, 1, "Select from multiple data inputs"),
    e("ManualSwitch", "Signal Routing", "Manual Switch", 2, 1, "Manually toggle between two inputs"),
    e("BusCreator", "Signal Routing", "Bus Creator", 2, 1, "Create bus signal from individual signals"),
    e("BusSelector", "Signal Routing", "Bus Selector", 1, 1, "Select signals from bus"),
    e("BusAssignment", "Signal Routing", "Bus Assignment", 2, 1, "Assign signals to bus elements"),
    e("BusToVector", "Signal Routing", "Bus to Vector", 1, 1, "Convert bus to vector signal"),
    e("Goto", "Signal Routing", "Goto", 1, 0, "Send signal to matching From block"),
    e("From", "Signal Routing", "From", 0, 1, "Receive signal from matching Goto block"),
    e("GotoTagVisibility", "Signal Routing", "Goto Tag Visibility", 0, 0, "Make Goto tag visible"),
    e("DataStoreRead", "Signal Routing", "Data Store Read", 0, 1, "Read from data store"),
    e("DataStoreWrite", "Signal Routing", "Data Store Write", 1, 0, "Write to data store"),
    e("DataStoreMemory", "Signal Routing", "Data Store Memory", 0, 0, "Define data store memory"),
    e("Merge", "Signal Routing", "Merge", 2, 1, "Merge multiple signals"),
    e("IndexVector", "Signal Routing", "Index Vector", 2, 1, "Index into vector"),
    e("Selector", "Signal Routing", "Selector", 1, 1, "Select elements by index"),
    e("Assignment", "Signal Routing", "Assignment", 2, 1, "Assign values to vector/matrix elements"),
    e("Concatenate", "Signal Routing", "Concatenate", 2, 1, "Concatenate signals"),
    e("VectorConcatenate", "Signal Routing", "Vector Concatenate", 2, 1, "Concatenate into vector"),
    e("MatrixConcatenate", "Signal Routing", "Matrix Concatenate", 2, 1, "Concatenate into matrix"),
    e("Permute", "Signal Routing", "Permute Dimensions", 1, 1, "Rearrange signal dimensions"),
    e("Squeeze", "Signal Routing", "Squeeze", 1, 1, "Remove singleton dimensions"),
    e("SignalConversion", "Signal Routing", "Signal Conversion", 1, 1, "Convert signal type"),
    e("InBus", "Signal Routing", "In Bus Element", 0, 1, "Input bus element"),
    e("Environment", "Signal Routing", "Environment Controller", 0, 2, "Switch between sim and codegen"),
    // ──── Signal Attributes ────
    e("DataTypeConversion", "Signal Attributes", "Data Type Conversion", 1, 1, "Convert between data types"),
    e("DataTypeDuplicate", "Signal Attributes", "Data Type Duplicate", 2, 0, "Ensure matching data types"),
    e("DataTypeScale", "Signal Attributes", "Data Type Scaling Strip", 1, 1, "Strip fixed-point scaling"),
    e("DataTypePropagation", "Signal Attributes", "Data Type Propagation", 3, 1, "Propagate data types"),
    e("SignalSpecification", "Signal Attributes", "Signal Specification", 1, 1, "Specify signal attributes"),
    e("IC", "Signal Attributes", "IC (Initial Condition)", 1, 1, "Set initial condition"),
    e("Width", "Signal Attributes", "Width", 1, 1, "Output signal width"),
    e("ProbeSignal", "Signal Attributes", "Probe", 1, 4, "Probe signal attributes"),
    e("WeightedSample", "Signal Attributes", "Weighted Sample Time", 1, 1, "Scale by sample time"),
    e("BusToSignal", "Signal Attributes", "Bus to Signal", 1, 1, "Convert bus to signal"),
    // ──── Subsystems ────
    // Subsystem ports are derived from the contained In/Outport blocks, so the
    // default (used when the model carries no <PortCounts>) is 0 in / 0 out.
    e("SubSystem", "Subsystems", "Subsystem", 0, 0, "Group blocks into subsystem"),
    e("AtomicSubSystem", "Subsystems", "Atomic Subsystem", 1, 1, "Atomic (non-virtual) subsystem"),
    e("EnabledSubSystem", "Subsystems", "Enabled Subsystem", 2, 1, "Subsystem with enable port"),
    e("TriggeredSubSystem", "Subsystems", "Triggered Subsystem", 2, 1, "Subsystem with trigger port"),
    e("EnabledTriggeredSubSystem", "Subsystems", "Enabled and Triggered", 3, 1, "Subsystem with enable and trigger"),
    e("ConditionalSubSystem", "Subsystems", "Conditional Subsystem", 2, 1, "Conditional execution subsystem"),
    e("ForEachSubSystem", "Subsystems", "For Each Subsystem", 1, 1, "Process each element independently"),
    e("ForIterator", "Subsystems", "For Iterator Subsystem", 1, 1, "Iterate N times"),
    e("WhileIterator", "Subsystems", "While Iterator Subsystem", 1, 1, "Iterate while condition is true"),
    e("IfAction", "Subsystems", "If Action Subsystem", 1, 1, "Execute when If condition is true"),
    e("SwitchCaseAction", "Subsystems", "Switch Case Action", 1, 1, "Execute for switch case match"),
    e("FunctionCallSubSystem", "Subsystems", "Function-Call Subsystem", 1, 1, "Call subsystem as function"),
    e("ConfigSubSystem", "Subsystems", "Configurable Subsystem", 1, 1, "Configurable subsystem variant"),
    e("VariantSubSystem", "Subsystems", "Variant Subsystem", 1, 1, "Compile-time variant selection"),
    e("ModelReference", "Subsystems", "Model Reference", 1, 1, "Reference external model"),
    e("IteratorSubSystem", "Subsystems", "Iterator", 1, 1, "Generic iteration subsystem"),
    e("CodeReuse", "Subsystems", "Code Reuse Subsystem", 1, 1, "Promote reusable code generation"),
    e("MaskedSubSystem", "Subsystems", "Masked Subsystem", 1, 1, "Subsystem with custom mask"),
    // ──── Ports & Subsystems ────
    e("EnablePort", "Ports & Subsystems", "Enable", 0, 0, "Enable port for subsystem"),
    e("TriggerPort", "Ports & Subsystems", "Trigger", 0, 0, "Trigger port for subsystem"),
    e("ActionPort", "Ports & Subsystems", "Action Port", 0, 0, "Action port for if/switch subsystem"),
    e("FunctionCallGenerator", "Ports & Subsystems", "Function-Call Generator", 0, 1, "Generate function calls"),
    e("If", "Ports & Subsystems", "If", 1, 1, "If-else conditional branching"),
    e("SwitchCase", "Ports & Subsystems", "Switch Case", 1, 2, "Switch-case branching"),
    e("FunctionCaller", "Ports & Subsystems", "Function Caller", 1, 1, "Call Simulink Function"),
    e("SimulinkFunction", "Ports & Subsystems", "Simulink Function", 1, 1, "Define Simulink function"),
    e("ArgumentInport", "Ports & Subsystems", "Argument Inport", 0, 1, "Function argument input"),
    e("ArgumentOutport", "Ports & Subsystems", "Argument Outport", 1, 0, "Function argument output"),
    e("InitializeFunction", "Ports & Subsystems", "Initialize Function", 0, 0, "Model initialize event"),
    e("TerminateFunction", "Ports & Subsystems", "Terminate Function", 0, 0, "Model terminate event"),
    e("ResetFunction", "Ports & Subsystems", "Reset Function", 0, 0, "Model reset event"),
    // ──── Lookup Tables ────
    e("Lookup", "Lookup Tables", "1-D Lookup Table", 1, 1, "One-dimensional lookup table"),
    e("Lookup2D", "Lookup Tables", "2-D Lookup Table", 2, 1, "Two-dimensional lookup table"),
    e("LookupND", "Lookup Tables", "n-D Lookup Table", 1, 1, "N-dimensional lookup table"),
    e("PreLookup", "Lookup Tables", "Prelookup", 1, 2, "Prelookup for interpolation index"),
    e("InterpUsingPreLookup", "Lookup Tables", "Interpolation Using Prelookup", 1, 1, "Interpolate using prelookup result"),
    e("DirectLookup", "Lookup Tables", "Direct Lookup Table (n-D)", 1, 1, "Direct index into table"),
    e("DynamicLookup", "Lookup Tables", "Dynamic Lookup", 3, 1, "Lookup with dynamic breakpoints"),
    e("LookupSine", "Lookup Tables", "Sine Lookup", 1, 1, "Sine approximation via table"),
    e("LookupCosine", "Lookup Tables", "Cosine Lookup", 1, 1, "Cosine approximation via table"),
    // ──── User-Defined Functions ────
    e("MATLAB Function", "User-Defined Functions", "MATLAB Function", 1, 1, "Embedded MATLAB function block"),
    e("CFunction", "User-Defined Functions", "C Function", 1, 1, "Call C/C++ code"),
    e("Fcn", "User-Defined Functions", "Fcn (Expression)", 1, 1, "Mathematical expression evaluator"),
    e("MATLABSystem", "User-Defined Functions", "MATLAB System", 1, 1, "MATLAB System object block"),
    e("SFunction", "User-Defined Functions", "S-Function", 1, 1, "S-Function (level-2 MEX)"),
    e("SFunctionBuilder", "User-Defined Functions", "S-Function Builder", 1, 1, "Generate S-Function code"),
    e("Level2MATLAB", "User-Defined Functions", "Level-2 MATLAB S-Function", 1, 1, "MATLAB-based S-Function"),
    e("InterpretedMATLAB", "User-Defined Functions", "Interpreted MATLAB Function", 1, 1, "Evaluate MATLAB expression"),
    e("EmbeddedMATLAB", "User-Defined Functions", "Embedded MATLAB Function", 1, 1, "Embedded MATLAB code block"),
    e("PythonFunction", "User-Defined Functions", "Python Function", 1, 1, "Call Python code"),
    // ──── Discontinuities ────
    e("Saturation", "Discontinuities", "Saturation", 1, 1, "Limit signal to bounds"),
    e("SaturationDynamic", "Discontinuities", "Saturation Dynamic", 3, 1, "Saturation with dynamic limits"),
    e("DeadZone", "Discontinuities", "Dead Zone", 1, 1, "Zero output within dead zone band"),
    e("DeadZoneDynamic", "Discontinuities", "Dead Zone Dynamic", 3, 1, "Dead zone with dynamic limits"),
    e("RateLimiter", "Discontinuities", "Rate Limiter", 1, 1, "Limit rate of change"),
    e("RateLimiterDynamic", "Discontinuities", "Rate Limiter Dynamic", 3, 1, "Rate limiter with dynamic limits"),
    e("Backlash", "Discontinuities", "Backlash", 1, 1, "Model backlash / hysteresis"),
    e("Coulomb", "Discontinuities", "Coulomb & Viscous Friction", 1, 1, "Coulomb and viscous friction"),
    e("HitCrossing", "Discontinuities", "Hit Crossing", 1, 1, "Detect zero-crossing event"),
    e("Quantizer", "Discontinuities", "Quantizer", 1, 1, "Quantize signal to fixed levels"),
    e("Relay", "Discontinuities", "Relay", 1, 1, "Switch output on/off with hysteresis"),
    e("WrappedToZero", "Discontinuities", "Wrap To Zero", 1, 1, "Wrap to zero on overflow"),
    // ──── Matrix Operations ────
    e("MatrixGain", "Matrix Operations", "Matrix Gain", 1, 1, "Gain by matrix multiplication"),
    e("Matrix Multiply", "Matrix Operations", "Matrix Multiply", 2, 1, "Multiply two matrices"),
    e("MatrixInverse", "Matrix Operations", "Matrix Inverse", 1, 1, "Compute matrix inverse"),
    e("Transpose", "Matrix Operations", "Transpose", 1, 1, "Transpose matrix"),
    e("Hermitian", "Matrix Operations", "Hermitian Transpose", 1, 1, "Conjugate transpose"),
    e("Hermitian Transpose", "Matrix Operations", "Hermitian Transpose", 1, 1, "Conjugate transpose (matrix library)"),
    e("MatrixDivide", "Matrix Operations", "Matrix Divide", 2, 1, "Solve AX=B (left divide)"),
    e("MatrixConcat", "Matrix Operations", "Matrix Concatenation", 2, 1, "Concatenate matrices"),
    e("SingularValues", "Matrix Operations", "Singular Value Decomposition", 1, 3, "SVD decomposition"),
    e("Eigenvalue", "Matrix Operations", "Eigenvalue", 1, 2, "Eigenvalue decomposition"),
    e("LUFactor", "Matrix Operations", "LU Factorization", 1, 2, "LU matrix factorization"),
    e("QRFactor", "Matrix Operations", "QR Factorization", 1, 2, "QR matrix factorization"),
    e("CholeskyFactor", "Matrix Operations", "Cholesky Factorization", 1, 1, "Cholesky factorization"),
    e("Determinant", "Matrix Operations", "Determinant", 1, 1, "Matrix determinant"),
    e("Trace", "Matrix Operations", "Trace", 1, 1, "Matrix trace"),
    e("MatrixRank", "Matrix Operations", "Rank", 1, 1, "Matrix rank"),
    e("PseudoInverse", "Matrix Operations", "Pseudo Inverse", 1, 1, "Moore-Penrose pseudoinverse"),
    e("Kronecker", "Matrix Operations", "Kronecker Product", 2, 1, "Kronecker tensor product"),
    e("EyeMatrix", "Matrix Operations", "Identity Matrix", 0, 1, "Generate identity matrix"),
    e("Identity Matrix", "Matrix Operations", "Identity Matrix (virtual)", 0, 1, "Identity matrix (matrix library)"),
    e("Is Triangular", "Matrix Operations", "Is Triangular", 1, 1, "Test if matrix is triangular"),
    e("Is Symmetric", "Matrix Operations", "Is Symmetric", 1, 1, "Test if matrix is symmetric"),
    e("Submatrix", "Matrix Operations", "Submatrix", 1, 1, "Extract a submatrix"),
    e("Matrix Square", "Matrix Operations", "Matrix Square", 1, 1, "Compute A'*A"),
    e("Permute Matrix", "Matrix Operations", "Permute Matrix", 2, 1, "Permute matrix columns"),
    e("Expand Scalar", "Matrix Operations", "Expand Scalar", 1, 1, "Turn scalar into matrix"),
    e("Is Hermitian", "Matrix Operations", "Is Hermitian", 1, 1, "Test if matrix is Hermitian"),
    e("Create Diagonal Matrix", "Matrix Operations", "Create Diagonal Matrix", 1, 1, "Create diagonal from vector"),
    e("Extract Diagonal", "Matrix Operations", "Extract Diagonal", 1, 1, "Extract diagonal of matrix"),
    e("Cross Product", "Matrix Operations", "Cross Product (matrix library)", 2, 1, "Vector cross product (matrix library virtual block)"),
    e("Matrix Concatenate", "Matrix Operations", "Matrix Concatenate (matrix library)", 2, 1, "Concatenate into matrix (matrix library virtual block)"),
    e("ToeplitzMatrix", "Matrix Operations", "Toeplitz Matrix", 1, 1, "Generate Toeplitz matrix"),
    // ──── Signal Processing ────
    e("FFT", "Signal Processing", "FFT", 1, 1, "Fast Fourier Transform"),
    e("IFFT", "Signal Processing", "IFFT", 1, 1, "Inverse Fast Fourier Transform"),
    e("AnalogFilter", "Signal Processing", "Analog Filter Design", 1, 1, "Butterworth/Chebyshev/Elliptic filter"),
    e("DigitalFilter", "Signal Processing", "Digital Filter Design", 1, 1, "Design and apply digital filter"),
    e("BiquadFilter", "Signal Processing", "Biquad Filter", 1, 1, "Second-order section (biquad) filter"),
    e("MedianFilter", "Signal Processing", "Median Filter", 1, 1, "Median filter"),
    e("LMSFilter", "Signal Processing", "LMS Filter", 2, 2, "Least mean squares adaptive filter"),
    e("RLSFilter", "Signal Processing", "RLS Filter", 2, 2, "Recursive least squares filter"),
    e("WindowFunction", "Signal Processing", "Window Function", 1, 1, "Apply window function"),
    e("Convolution", "Signal Processing", "Convolution", 2, 1, "Signal convolution"),
    e("Correlation", "Signal Processing", "Correlation", 2, 1, "Signal cross-correlation"),
    e("Autocorrelation", "Signal Processing", "Autocorrelation", 1, 1, "Signal autocorrelation"),
    e("DCT", "Signal Processing", "DCT", 1, 1, "Discrete Cosine Transform"),
    e("IDCT", "Signal Processing", "IDCT", 1, 1, "Inverse Discrete Cosine Transform"),
    e("Hilbert", "Signal Processing", "Hilbert Transform", 1, 1, "Hilbert transform"),
    e("Spectrum", "Signal Processing", "Spectrum Analyzer", 1, 0, "Frequency spectrum analysis"),
    e("Spectrogram", "Signal Processing", "Spectrogram", 1, 1, "Time-frequency spectrogram"),
    e("PowerSpectrum", "Signal Processing", "Power Spectrum", 1, 1, "Power spectral density"),
    e("SignalEnvelope", "Signal Processing", "Envelope Detector", 1, 1, "Signal envelope extraction"),
    e("ZeroCrossingCount", "Signal Processing", "Zero-Crossing Counter", 1, 1, "Count zero crossings"),
    e("PeakDetector", "Signal Processing", "Peak Detector", 1, 2, "Find signal peaks"),
    e("Interpolation", "Signal Processing", "Interpolation", 1, 1, "Signal interpolation"),
    e("Decimation", "Signal Processing", "Decimation", 1, 1, "Signal decimation"),
    e("Resampler", "Signal Processing", "Resampler", 1, 1, "Multi-rate resampling"),
    e("OverlapAdd", "Signal Processing", "Overlap-Add", 1, 1, "Block-based signal processing"),
    // ──── Control System ────
    e("LTISystem", "Control System", "LTI System", 1, 1, "Linear time-invariant system"),
    e("PIDCompact", "Control System", "PID Controller (Compact)", 1, 1, "Compact PID block"),
    e("LQR", "Control System", "LQR Controller", 1, 1, "Linear quadratic regulator"),
    e("LQG", "Control System", "LQG Controller", 1, 1, "Linear quadratic Gaussian"),
    e("KalmanFilter", "Control System", "Kalman Filter", 2, 2, "Standard Kalman filter"),
    e("ExtendedKalman", "Control System", "Extended Kalman Filter", 2, 2, "Extended Kalman filter"),
    e("UnscentedKalman", "Control System", "Unscented Kalman Filter", 2, 2, "Unscented Kalman filter"),
    e("ParticleFilter", "Control System", "Particle Filter", 2, 2, "Particle filter / sequential Monte Carlo"),
    e("Observer", "Control System", "State Observer", 2, 1, "Luenberger state observer"),
    e("ModelPredictive", "Control System", "MPC Controller", 2, 1, "Model predictive controller"),
    e("GainSchedule", "Control System", "Gain Scheduling", 2, 1, "Gain-scheduled controller"),
    e("AdaptiveController", "Control System", "Adaptive Controller", 2, 1, "Adaptive control block"),
    e("NotchFilter", "Control System", "Notch Filter", 1, 1, "Notch (band-stop) filter"),
    e("Compensator", "Control System", "Lead-Lag Compensator", 1, 1, "Frequency-domain compensator"),
    e("AntiWindup", "Control System", "Anti-Windup", 2, 1, "Integrator anti-windup"),
    // ──── Stateflow ────
    e("Chart", "Stateflow", "Chart", 1, 1, "Stateflow chart"),
    e("StateTransitionTable", "Stateflow", "State Transition Table", 1, 1, "State transition table"),
    e("TruthTable", "Stateflow", "Truth Table", 1, 1, "Truth table"),
    e("SequenceViewer", "Stateflow", "Sequence Viewer", 1, 0, "Sequence viewer"),
    // ──── Physical Modeling ────
    e("SimscapeBlock", "Physical Modeling", "Simscape Block", 1, 1, "Simscape physical model block"),
    e("SimscapeConnection", "Physical Modeling", "Connection Port", 0, 0, "Simscape connection port"),
    e("PSConvert", "Physical Modeling", "PS-Simulink Converter", 1, 1, "Physical signal to Simulink"),
    e("SPConvert", "Physical Modeling", "Simulink-PS Converter", 1, 1, "Simulink to physical signal"),
    e("SimscapeSolver", "Physical Modeling", "Solver Configuration", 0, 0, "Simscape solver config"),
    e("SpringDamper", "Physical Modeling", "Spring-Damper", 2, 1, "Spring-damper mechanical element"),
    e("RotationalSpring", "Physical Modeling", "Rotational Spring", 1, 1, "Rotational spring"),
    e("RotationalDamper", "Physical Modeling", "Rotational Damper", 1, 1, "Rotational damper"),
    e("MassBlock", "Physical Modeling", "Mass", 1, 1, "Translational mass"),
    e("InertiaBlock", "Physical Modeling", "Inertia", 1, 1, "Rotational inertia"),
    e("IdealForceSource", "Physical Modeling", "Ideal Force Source", 1, 1, "Ideal force source"),
    e("IdealTorqueSource", "Physical Modeling", "Ideal Torque Source", 1, 1, "Ideal torque source"),
    e("MechanicalRef", "Physical Modeling", "Mechanical Translational Reference", 0, 0, "Translational reference"),
    e("RotationalRef", "Physical Modeling", "Rotational Reference", 0, 0, "Rotational reference"),
    e("Resistor", "Physical Modeling", "Resistor", 0, 0, "Electrical resistor"),
    e("Capacitor", "Physical Modeling", "Capacitor", 0, 0, "Electrical capacitor"),
    e("Inductor", "Physical Modeling", "Inductor", 0, 0, "Electrical inductor"),
    e("Diode", "Physical Modeling", "Diode", 0, 0, "Electrical diode"),
    e("VoltageSource", "Physical Modeling", "Voltage Source", 0, 0, "DC voltage source"),
    e("CurrentSource", "Physical Modeling", "Current Source", 0, 0, "DC current source"),
    e("ElectricalRef", "Physical Modeling", "Electrical Reference", 0, 0, "Ground node"),
    e("VoltageSensor", "Physical Modeling", "Voltage Sensor", 0, 1, "Measure voltage"),
    e("CurrentSensor", "Physical Modeling", "Current Sensor", 0, 1, "Measure current"),
    e("Pipe", "Physical Modeling", "Pipe", 0, 0, "Hydraulic pipe"),
    e("HydraulicPump", "Physical Modeling", "Hydraulic Pump", 1, 0, "Hydraulic pump"),
    e("HydraulicMotor", "Physical Modeling", "Hydraulic Motor", 0, 1, "Hydraulic motor"),
    e("HydraulicCylinder", "Physical Modeling", "Hydraulic Cylinder", 1, 1, "Hydraulic cylinder"),
    e("FluidReservoir", "Physical Modeling", "Fluid Reservoir", 0, 0, "Fluid reservoir"),
    e("ThermalMass", "Physical Modeling", "Thermal Mass", 0, 0, "Thermal mass"),
    e("HeatExchanger", "Physical Modeling", "Heat Exchanger", 0, 0, "Thermal heat exchanger"),
    // ──── Robotics ────
    e("RigidBodyTree", "Robotics", "Rigid Body Tree", 1, 1, "Multi-body robot model"),
    e("ForwardKinematics", "Robotics", "Forward Kinematics", 1, 1, "Compute forward kinematics"),
    e("InverseKinematics", "Robotics", "Inverse Kinematics", 2, 1, "Compute inverse kinematics"),
    e("Jacobian", "Robotics", "Geometric Jacobian", 1, 1, "Compute Jacobian matrix"),
    e("InverseDynamics", "Robotics", "Inverse Dynamics", 3, 1, "Compute inverse dynamics torques"),
    e("ForwardDynamics", "Robotics", "Forward Dynamics", 2, 2, "Compute forward dynamics"),
    e("GravityCompensation", "Robotics", "Gravity Compensation", 1, 1, "Compute gravity torques"),
    e("MassMatrix", "Robotics", "Mass Matrix", 1, 1, "Compute manipulator inertia matrix"),
    e("CoriolisMatrix", "Robotics", "Coriolis Matrix", 2, 1, "Compute Coriolis matrix"),
    e("JointSpaceMotion", "Robotics", "Joint Space Motion Model", 2, 2, "Joint space motion model"),
    e("TaskSpaceMotion", "Robotics", "Task Space Motion Model", 2, 2, "Task space motion model"),
    e("TrajectoryGenerator", "Robotics", "Trajectory Generator", 1, 1, "Generate joint trajectories"),
    e("WaypointFollower", "Robotics", "Waypoint Follower", 2, 1, "Follow waypoint path"),
    e("PurePursuit", "Robotics", "Pure Pursuit", 2, 2, "Pure pursuit path tracking"),
    e("JointActuator", "Robotics", "Joint Actuator", 1, 0, "Actuate robot joints"),
    e("JointSensor", "Robotics", "Joint Sensor", 0, 1, "Sense joint states"),
    e("BodyActuator", "Robotics", "Body Actuator", 1, 0, "Apply body forces/torques"),
    e("TransformSensor", "Robotics", "Transform Sensor", 0, 1, "Sense body transforms"),
    e("RobotRigidBody", "Robotics", "Rigid Body", 2, 2, "Rigid body dynamics"),
    e("RobotJoint", "Robotics", "Joint", 2, 2, "Joint (revolute/prismatic)"),
    e("RobotForwardKin", "Robotics", "Forward Kinematics", 1, 1, "Forward kinematics solver"),
    e("RobotInverseKin", "Robotics", "Inverse Kinematics", 1, 1, "Inverse kinematics solver"),
    e("RobotTrajectory", "Robotics", "Trajectory Generator", 1, 1, "Trajectory planning"),
    e("RobotCollision", "Robotics", "Collision Check", 2, 1, "Collision detection between bodies"),
    e("RobotTransformTree", "Robotics", "Transform Tree", 1, 1, "Coordinate frame tree"),
    e("RobotPID", "Robotics", "Joint PID", 2, 1, "Joint-level PID controller"),
    // ──── Aerospace / Navigation ────
    e("QuaternionMultiply", "Aerospace / Navigation", "Quaternion Multiplication", 2, 1, "Multiply quaternions"),
    e("QuaternionInverse", "Aerospace / Navigation", "Quaternion Inverse", 1, 1, "Inverse of quaternion"),
    e("QuaternionNorm", "Aerospace / Navigation", "Quaternion Norm", 1, 1, "Norm of quaternion"),
    e("QuaternionNormalize", "Aerospace / Navigation", "Quaternion Normalize", 1, 1, "Normalize quaternion"),
    e("QuaternionToEuler", "Aerospace / Navigation", "Quaternion to Euler", 1, 1, "Convert quaternion to Euler angles"),
    e("EulerToQuaternion", "Aerospace / Navigation", "Euler to Quaternion", 1, 1, "Convert Euler to quaternion"),
    e("QuaternionToRotMatrix", "Aerospace / Navigation", "Quaternion to DCM", 1, 1, "Quaternion to direction cosine matrix"),
    e("RotMatrixToQuaternion", "Aerospace / Navigation", "DCM to Quaternion", 1, 1, "DCM to quaternion"),
    e("EulerToRotMatrix", "Aerospace / Navigation", "Euler to DCM", 1, 1, "Euler angles to DCM"),
    e("RotMatrixToEuler", "Aerospace / Navigation", "DCM to Euler", 1, 1, "DCM to Euler angles"),
    e("AxisAngleToQuat", "Aerospace / Navigation", "Axis-Angle to Quaternion", 1, 1, "Convert axis-angle to quaternion"),
    e("QuatToAxisAngle", "Aerospace / Navigation", "Quaternion to Axis-Angle", 1, 1, "Convert quaternion to axis-angle"),
    e("AngularVelocity", "Aerospace / Navigation", "Angular Velocity", 1, 1, "Compute angular velocity"),
    e("CoordinateTransform", "Aerospace / Navigation", "Coordinate Transformation", 1, 1, "Transform coordinates between frames"),
    e("FrameRotation", "Aerospace / Navigation", "Frame Rotation", 2, 1, "Rotate frame by angle/quaternion"),
    e("FlatEarthDynamics", "Aerospace / Navigation", "Flat Earth Dynamics", 4, 4, "6-DOF flat earth equations of motion"),
    e("WindModel", "Aerospace / Navigation", "Wind Model", 1, 1, "Atmospheric wind model"),
    e("GravityModel", "Aerospace / Navigation", "Gravity Model", 1, 1, "Gravitational field model"),
    e("AtmosphereModel", "Aerospace / Navigation", "Atmosphere Model", 1, 3, "Standard atmosphere properties"),
    e("AeroCoefficients", "Aerospace / Navigation", "Aerodynamic Coefficients", 3, 3, "Compute aero forces/moments"),
    e("GPSSensor", "Aerospace / Navigation", "GPS Sensor", 1, 3, "GPS position/velocity sensor model"),
    e("IMUSensor", "Aerospace / Navigation", "IMU Sensor", 2, 2, "Inertial measurement unit model"),
    e("MagnetometerSensor", "Aerospace / Navigation", "Magnetometer", 1, 1, "Magnetic field sensor model"),
    e("BarometerSensor", "Aerospace / Navigation", "Barometer", 1, 1, "Barometric pressure sensor model"),
    e("AHRS", "Aerospace / Navigation", "AHRS Filter", 3, 1, "Attitude heading reference system"),
    e("ComplementaryFilter", "Aerospace / Navigation", "Complementary Filter", 2, 1, "Complementary filter for IMU"),
    e("INS", "Aerospace / Navigation", "INS Filter", 3, 2, "Inertial navigation system filter"),
    // ──── Communications ────
    e("UDPSend", "Communications", "UDP Send", 1, 0, "Send data via UDP"),
    e("UDPReceive", "Communications", "UDP Receive", 0, 1, "Receive data via UDP"),
    e("TCPIPSend", "Communications", "TCP/IP Send", 1, 0, "Send data via TCP/IP"),
    e("TCPIPReceive", "Communications", "TCP/IP Receive", 0, 1, "Receive data via TCP/IP"),
    e("SerialSend", "Communications", "Serial Send", 1, 0, "Send data via serial port"),
    e("SerialReceive", "Communications", "Serial Receive", 0, 1, "Receive data via serial port"),
    e("CANTransmit", "Communications", "CAN Transmit", 1, 0, "Send CAN message"),
    e("CANReceive", "Communications", "CAN Receive", 0, 1, "Receive CAN message"),
    e("CANPack", "Communications", "CAN Pack", 1, 1, "Pack signals into CAN message"),
    e("CANUnpack", "Communications", "CAN Unpack", 1, 1, "Unpack signals from CAN message"),
    e("SharedMemoryRead", "Communications", "Shared Memory Read", 0, 1, "Read from shared memory"),
    e("SharedMemoryWrite", "Communications", "Shared Memory Write", 1, 0, "Write to shared memory"),
    e("MQTTPublish", "Communications", "MQTT Publish", 1, 0, "Publish MQTT message"),
    e("MQTTSubscribe", "Communications", "MQTT Subscribe", 0, 1, "Subscribe to MQTT topic"),
    e("ROSPublisher", "Communications", "ROS Publisher", 1, 0, "Publish to ROS topic"),
    e("ROSSubscriber", "Communications", "ROS Subscriber", 0, 1, "Subscribe to ROS topic"),
    e("ROSServiceClient", "Communications", "ROS Service Client", 1, 1, "Call ROS service"),
    e("ROSServiceServer", "Communications", "ROS Service Server", 1, 1, "Serve ROS service requests"),
    e("ROS2Publisher", "Communications", "ROS 2 Publisher", 1, 0, "Publish to ROS 2 topic"),
    e("ROS2Subscriber", "Communications", "ROS 2 Subscriber", 0, 1, "Subscribe to ROS 2 topic"),
    e("EtherCAT", "Communications", "EtherCAT", 1, 1, "EtherCAT communication"),
    e("ProfinetIO", "Communications", "PROFINET IO", 1, 1, "PROFINET IO communication"),
    e("OPCUARead", "Communications", "OPC UA Read", 0, 1, "Read OPC UA node"),
    e("OPCUAWrite", "Communications", "OPC UA Write", 1, 0, "Write OPC UA node"),
    e("Modbus", "Communications", "Modbus", 1, 1, "Modbus communication"),
    e("CommAWGN", "Communications", "AWGN Channel", 1, 1, "Additive white Gaussian noise channel"),
    e("CommBPSKMod", "Communications", "BPSK Modulator", 1, 1, "BPSK modulation"),
    e("CommBPSKDemod", "Communications", "BPSK Demodulator", 1, 1, "BPSK demodulation"),
    e("CommQPSKMod", "Communications", "QPSK Modulator", 1, 1, "QPSK modulation"),
    e("CommQPSKDemod", "Communications", "QPSK Demodulator", 1, 1, "QPSK demodulation"),
    e("CommQAMMod", "Communications", "QAM Modulator", 1, 1, "QAM modulation"),
    e("CommQAMDemod", "Communications", "QAM Demodulator", 1, 1, "QAM demodulation"),
    e("CommFMMod", "Communications", "FM Modulator", 1, 1, "FM modulation"),
    e("CommFMDemod", "Communications", "FM Demodulator", 1, 1, "FM demodulation"),
    e("CommAMMod", "Communications", "AM Modulator", 1, 1, "AM modulation"),
    e("CommAMDemod", "Communications", "AM Demodulator", 1, 1, "AM demodulation"),
    e("CommConvEnc", "Communications", "Convolutional Encoder", 1, 1, "Convolutional encoding"),
    e("CommViterbi", "Communications", "Viterbi Decoder", 1, 1, "Viterbi decoding"),
    e("CommCRC", "Communications", "CRC Generator", 1, 1, "CRC generation"),
    e("CommInterleaver", "Communications", "Interleaver", 1, 1, "Block interleaving"),
    e("CommRaisedCosine", "Communications", "Raised Cosine Filter", 1, 1, "Raised cosine TX/RX filter"),
    // ──── Image Processing ────
    e("ImageResize", "Image Processing", "Image Resize", 1, 1, "Resize image"),
    e("ImageRotate", "Image Processing", "Image Rotate", 1, 1, "Rotate image by angle"),
    e("ImageCrop", "Image Processing", "Image Crop", 1, 1, "Crop image region"),
    e("ColorConversion", "Image Processing", "Color Space Conversion", 1, 1, "Convert between RGB/HSV/YCbCr/Grayscale"),
    e("EdgeDetection", "Image Processing", "Edge Detection", 1, 1, "Detect edges (Sobel, Canny, Prewitt)"),
    e("Morphology", "Image Processing", "Morphological Operation", 1, 1, "Erosion, dilation, opening, closing"),
    e("BlobAnalysis", "Image Processing", "Blob Analysis", 1, 3, "Find and analyze connected regions"),
    e("TemplateMatch", "Image Processing", "Template Matching", 2, 1, "Find template in image"),
    e("Threshold", "Image Processing", "Image Threshold", 1, 1, "Binary threshold on image"),
    e("HistogramEqualize", "Image Processing", "Histogram Equalization", 1, 1, "Equalize image histogram"),
    e("GaussianBlur", "Image Processing", "Gaussian Blur", 1, 1, "Gaussian smoothing filter"),
    e("MedianFilterImg", "Image Processing", "Median Filter (Image)", 1, 1, "Median filter for images"),
    e("HoughTransform", "Image Processing", "Hough Transform", 1, 1, "Hough transform for lines/circles"),
    e("FeatureExtract", "Image Processing", "Feature Extraction", 1, 1, "Extract image features (SURF, ORB)"),
    e("OpticalFlow", "Image Processing", "Optical Flow", 1, 1, "Compute optical flow"),
    e("VideoDisplay", "Image Processing", "Video Display", 1, 0, "Display video stream"),
    e("VideoCapture", "Image Processing", "Video Capture", 0, 1, "Capture from camera"),
    e("VideoFileReader", "Image Processing", "Video File Reader", 0, 1, "Read video from file"),
    e("VideoFileWriter", "Image Processing", "Video File Writer", 1, 0, "Write video to file"),
    e("DrawShapes", "Image Processing", "Draw Shapes", 2, 1, "Draw shapes on image"),
    e("InsertText", "Image Processing", "Insert Text", 2, 1, "Insert text into image"),
    e("ImageComposite", "Image Processing", "Image Composite", 2, 1, "Composite two images"),
    e("PointCloudDisplay", "Image Processing", "Point Cloud Display", 1, 0, "Display 3D point cloud"),
    e("DepthEstimation", "Image Processing", "Depth Estimation", 2, 1, "Stereo depth estimation"),
    // ──── AI / Deep Learning ────
    e("PredictBlock", "AI / Deep Learning", "Predict", 1, 1, "Run deep learning inference"),
    e("ClassificationBlock", "AI / Deep Learning", "Image Classifier", 1, 1, "Image classification network"),
    e("ObjectDetector", "AI / Deep Learning", "Object Detector", 1, 2, "Object detection (YOLO, SSD, etc.)"),
    e("SemanticSegmentation", "AI / Deep Learning", "Semantic Segmentation", 1, 1, "Pixel-wise segmentation"),
    e("InstanceSegmentation", "AI / Deep Learning", "Instance Segmentation", 1, 2, "Instance segmentation"),
    e("PoseEstimation", "AI / Deep Learning", "Pose Estimation", 1, 1, "Human / object pose estimation"),
    e("ReinforcementLearning", "AI / Deep Learning", "RL Agent", 2, 1, "Reinforcement learning agent"),
    e("NeuralNetwork", "AI / Deep Learning", "Neural Network", 1, 1, "Custom neural network block"),
    e("ONNXModel", "AI / Deep Learning", "ONNX Model", 1, 1, "Import and run ONNX model"),
    e("TensorFlowModel", "AI / Deep Learning", "TensorFlow Model", 1, 1, "Import TensorFlow model"),
    e("FuzzyLogicController", "AI / Deep Learning", "Fuzzy Logic Controller", 1, 1, "Fuzzy inference system"),
    e("NeuralFit", "AI / Deep Learning", "Neural Fitting", 1, 1, "Neural network function fitting"),
    // ──── Statistics ────
    e("Mean", "Statistics", "Mean", 1, 1, "Compute running mean"),
    e("Variance", "Statistics", "Variance", 1, 1, "Compute running variance"),
    e("StandardDeviation", "Statistics", "Standard Deviation", 1, 1, "Compute running std dev"),
    e("RMS", "Statistics", "RMS", 1, 1, "Root mean square"),
    e("Minimum", "Statistics", "Minimum", 1, 1, "Running minimum"),
    e("Maximum", "Statistics", "Maximum", 1, 1, "Running maximum"),
    e("MovingMean", "Statistics", "Moving Mean", 1, 1, "Sliding window mean"),
    e("MovingVariance", "Statistics", "Moving Variance", 1, 1, "Sliding window variance"),
    e("MovingRMS", "Statistics", "Moving RMS", 1, 1, "Sliding window RMS"),
    e("Histogram", "Statistics", "Histogram", 1, 1, "Histogram of signal values"),
    e("CumulativeSum", "Statistics", "Cumulative Sum", 1, 1, "Running cumulative sum"),
    e("CumulativeProd", "Statistics", "Cumulative Product", 1, 1, "Running cumulative product"),
    e("Sort", "Statistics", "Sort", 1, 1, "Sort vector elements"),
    // ──── Code Generation ────
    e("CodeAnnotation", "Code Generation", "Code Annotation", 0, 0, "Annotate generated code"),
    e("TargetHardware", "Code Generation", "Target Hardware", 0, 0, "Target hardware configuration"),
    e("ProcessorInLoop", "Code Generation", "Processor-in-the-Loop", 1, 1, "PIL testing block"),
    e("SoftwareInLoop", "Code Generation", "Software-in-the-Loop", 1, 1, "SIL testing block"),
    e("ExternalMode", "Code Generation", "External Mode Control", 0, 0, "External mode interface"),
    e("SignalLogging", "Code Generation", "Signal Logging", 1, 0, "Log signal for code gen"),
    e("DataObjectConfig", "Code Generation", "Data Object", 0, 0, "Configure data for code gen"),
    // ──── Testing & Verification ────
    e("TestAssessment", "Testing & Verification", "Test Assessment", 1, 0, "Assess test criteria"),
    e("TestSequence", "Testing & Verification", "Test Sequence", 0, 1, "Define test sequences"),
    e("Assertion", "Testing & Verification", "Assertion", 1, 0, "Assert condition during simulation"),
    e("CheckStaticRange", "Testing & Verification", "Check Static Range", 1, 1, "Verify static range"),
    e("CheckDynamicRange", "Testing & Verification", "Check Dynamic Range", 1, 1, "Verify dynamic range"),
    e("CheckStaticGap", "Testing & Verification", "Check Static Gap", 1, 1, "Verify no gap"),
    e("CheckStaticLower", "Testing & Verification", "Check Static Lower Bound", 1, 1, "Verify lower bound"),
    e("CheckStaticUpper", "Testing & Verification", "Check Static Upper Bound", 1, 1, "Verify upper bound"),
    e("CheckGradient", "Testing & Verification", "Check Gradient", 1, 1, "Verify signal gradient"),
    e("CheckResolution", "Testing & Verification", "Check Resolution", 1, 1, "Verify signal resolution"),
    e("ProofAssumption", "Testing & Verification", "Proof Assumption", 1, 1, "Formal verification assumption"),
    e("ProofObjective", "Testing & Verification", "Proof Objective", 1, 0, "Formal verification objective"),
    // ──── Commonly Used ────
    e("DataTypeConv", "Commonly Used", "Convert", 1, 1, "Quick data type converter"),
    e("SubsystemRef", "Commonly Used", "Subsystem Reference", 1, 1, "Reference to external subsystem file"),
    e("DocBlock", "Commonly Used", "DocBlock", 0, 0, "Document block"),
    e("Model", "Commonly Used", "Model", 0, 0, "Model reference block"),
    e("Abstraction", "Commonly Used", "Signal Hierarchy", 1, 1, "Signal abstraction layer"),
    // ──── Power Electronics ────
    e("IGBT", "Power Electronics", "IGBT", 0, 0, "IGBT power switch"),
    e("MOSFET", "Power Electronics", "MOSFET", 0, 0, "MOSFET power switch"),
    e("ThyristorBlock", "Power Electronics", "Thyristor", 0, 0, "Thyristor"),
    e("InverterBlock", "Power Electronics", "Inverter", 1, 1, "Power inverter"),
    e("RectifierBlock", "Power Electronics", "Rectifier", 1, 1, "Power rectifier"),
    e("DCDCConverter", "Power Electronics", "DC-DC Converter", 1, 1, "DC-DC buck/boost converter"),
    e("PWMGenerator", "Power Electronics", "PWM Generator", 1, 1, "PWM signal generator"),
    e("ThreePhaseSource", "Power Electronics", "Three-Phase Source", 0, 3, "Three-phase AC source"),
    e("ThreePhaseMeasure", "Power Electronics", "Three-Phase Measurement", 3, 3, "Three-phase VI measurement"),
    e("ABCToDQ0", "Power Electronics", "abc to dq0 Transform", 2, 1, "Park transformation"),
    e("DQ0ToABC", "Power Electronics", "dq0 to abc Transform", 2, 1, "Inverse Park transform"),
    e("AlphaBetaToABC", "Power Electronics", "αβ to abc Transform", 1, 1, "Inverse Clarke transform"),
    e("ABCToAlphaBeta", "Power Electronics", "abc to αβ Transform", 1, 1, "Clarke transform"),
    e("PLL", "Power Electronics", "Phase-Locked Loop", 1, 2, "Phase-locked loop"),
    e("HBridge", "Power Electronics", "H-Bridge", 1, 1, "H-bridge motor driver"),
    e("BatteryModel", "Power Electronics", "Battery", 1, 1, "Battery model"),
    e("SolarCell", "Power Electronics", "Solar Cell", 0, 1, "Photovoltaic cell model"),
    e("Transformer", "Power Electronics", "Transformer", 0, 0, "Electrical transformer"),
    e("Motor", "Power Electronics", "Motor", 1, 1, "Electric motor model"),
    e("PEMosfet", "Power Electronics", "MOSFET", 2, 2, "MOSFET switch model"),
    e("PEIGBT", "Power Electronics", "IGBT", 2, 2, "IGBT switch model"),
    e("PEDiode", "Power Electronics", "Power Diode", 1, 1, "Power diode model"),
    e("PEBuckConverter", "Power Electronics", "Buck Converter", 2, 1, "DC-DC buck converter"),
    e("PEBoostConverter", "Power Electronics", "Boost Converter", 2, 1, "DC-DC boost converter"),
    e("PEBuckBoost", "Power Electronics", "Buck-Boost", 2, 1, "DC-DC buck-boost converter"),
    e("PEFullBridge", "Power Electronics", "Full Bridge", 2, 2, "H-bridge inverter"),
    e("PEThreePhaseInv", "Power Electronics", "3-Phase Inverter", 2, 3, "Three-phase voltage source inverter"),
    e("PEPWMGenerator", "Power Electronics", "PWM Generator", 1, 1, "PWM signal generator"),
    e("PERectifier", "Power Electronics", "Rectifier", 1, 1, "AC/DC rectifier"),
    // ──── HDL / FPGA ────
    e("HDLCounter", "HDL / FPGA", "HDL Counter", 0, 1, "HDL-compatible counter"),
    e("HDLDelay", "HDL / FPGA", "HDL Delay", 1, 1, "HDL-compatible delay"),
    e("HDLFIFORead", "HDL / FPGA", "HDL FIFO Read", 1, 2, "HDL FIFO read interface"),
    e("HDLFIFOWrite", "HDL / FPGA", "HDL FIFO Write", 2, 1, "HDL FIFO write interface"),
    e("DualPortRAM", "HDL / FPGA", "Dual Port RAM", 2, 2, "Dual port RAM"),
    e("SinglePortRAM", "HDL / FPGA", "Single Port RAM", 1, 1, "Single port RAM"),
    e("Serializer", "HDL / FPGA", "Serializer", 1, 1, "Parallel to serial"),
    e("Deserializer", "HDL / FPGA", "Deserializer", 1, 1, "Serial to parallel"),
    e("BitConcat", "HDL / FPGA", "Bit Concat", 2, 1, "Concatenate bit fields"),
    e("BitSlice", "HDL / FPGA", "Bit Slice", 1, 1, "Extract bit slice"),
    e("HDLSubsystem", "HDL / FPGA", "HDL Subsystem", 1, 1, "Subsystem for HDL code gen"),
    // ──── Timing & Scheduling ────
    e("SampleTime", "Timing & Scheduling", "Specify Sample Time", 1, 1, "Override sample time"),
    e("HitCross", "Timing & Scheduling", "Hit Crossing", 1, 1, "Detect exact crossing events"),
    e("EventListener", "Timing & Scheduling", "Event Listener", 0, 1, "Listen for events"),
    e("EventBroadcast", "Timing & Scheduling", "Event Broadcast", 1, 0, "Broadcast event"),
    e("Timer", "Timing & Scheduling", "Timer", 0, 1, "Generate timer events"),
    e("TaskSync", "Timing & Scheduling", "Task Synchronizer", 1, 1, "Synchronize concurrent tasks"),
    e("RateSelector", "Timing & Scheduling", "Rate Selector", 1, 1, "Select execution rate"),
    // ──── Automotive ────
    e("EngineModel", "Automotive", "Engine Model", 2, 2, "IC engine model"),
    e("TransmissionModel", "Automotive", "Transmission", 2, 2, "Gear transmission model"),
    e("VehicleDynamics", "Automotive", "Vehicle Body", 3, 3, "Vehicle body dynamics"),
    e("TireModel", "Automotive", "Tire Model", 2, 2, "Tire force model"),
    e("BrakeModel", "Automotive", "Brake System", 1, 1, "Brake actuator model"),
    e("SteeringModel", "Automotive", "Steering System", 1, 1, "Steering dynamics"),
    e("DriverModel", "Automotive", "Driver Model", 2, 2, "Human driver model"),
    e("ABSController", "Automotive", "ABS Controller", 2, 1, "Anti-lock braking system"),
    e("ESCController", "Automotive", "ESC Controller", 3, 1, "Electronic stability control"),
    e("CruiseControl", "Automotive", "Cruise Control", 2, 1, "Cruise control logic"),
    e("AdaptiveCruise", "Automotive", "Adaptive Cruise Control", 3, 1, "ACC with radar input"),
    e("LaneKeep", "Automotive", "Lane Keep Assist", 2, 1, "Lane keeping controller"),
    e("ParkingAssist", "Automotive", "Parking Assist", 3, 1, "Parking assistant"),
    e("RadarModel", "Automotive", "Radar Sensor", 1, 2, "Automotive radar model"),
    e("LidarModel", "Automotive", "Lidar Sensor", 1, 2, "Lidar point cloud model"),
    e("CameraModel", "Automotive", "Camera Sensor", 1, 1, "Vision camera model"),
    e("UltrasonicSensor", "Automotive", "Ultrasonic Sensor", 1, 1, "Proximity sensor model"),
    e("AutoEngine", "Automotive", "Engine", 2, 2, "Internal combustion engine model"),
    e("AutoTransmission", "Automotive", "Transmission", 2, 2, "Automatic/manual transmission"),
    e("AutoTire", "Automotive", "Tire", 2, 2, "Tire dynamics model"),
    e("AutoBrake", "Automotive", "Brake System", 2, 1, "Brake system model"),
    e("AutoSteering", "Automotive", "Steering", 1, 1, "Steering system model"),
    e("AutoChassis", "Automotive", "Vehicle Chassis", 4, 4, "Vehicle chassis dynamics"),
    e("AutoDriveline", "Automotive", "Driveline", 2, 2, "Driveline/drivetrain model"),
    e("AutoBattery", "Automotive", "Battery", 2, 2, "Battery model"),
    e("AutoMotorElec", "Automotive", "Electric Motor", 2, 2, "Electric motor model"),
    e("AutoInverter", "Automotive", "Inverter", 2, 2, "DC/AC inverter model"),
    // ──── Audio ────
    e("AudioSource", "Audio", "Audio File Source", 0, 1, "Read audio from file"),
    e("AudioSink", "Audio", "Audio File Sink", 1, 0, "Write audio to file"),
    e("AudioPlayer", "Audio", "Audio Device Writer", 1, 0, "Play audio through device"),
    e("AudioCapture", "Audio", "Audio Device Reader", 0, 1, "Record from microphone"),
    e("AudioEqualizer", "Audio", "Parametric EQ Filter", 1, 1, "Parametric equalizer"),
    e("AudioCompressor", "Audio", "Dynamic Range Compressor", 1, 1, "Audio compressor"),
    e("AudioLimiter", "Audio", "Dynamic Range Limiter", 1, 1, "Audio limiter"),
    e("AudioGate", "Audio", "Noise Gate", 1, 1, "Audio noise gate"),
    e("AudioReverb", "Audio", "Reverb", 1, 1, "Reverberation effect"),
    e("AudioDelay", "Audio", "Audio Delay", 1, 1, "Time delay effect"),
    e("AudioMixer", "Audio", "Audio Mixer", 2, 1, "Mix audio channels"),
    e("AudioOscillator", "Audio", "Audio Oscillator", 0, 1, "Generate audio waveform"),
    e("AudioPitch", "Audio", "Pitch Shift", 1, 1, "Shift audio pitch"),
    e("AudioTimeStretch", "Audio", "Time Stretch", 1, 1, "Time-stretch audio"),
    // ──── Machine Learning ────
    e("ClassificationTree", "Machine Learning", "Classification Tree", 1, 1, "Decision tree classifier"),
    e("RegressionTree", "Machine Learning", "Regression Tree", 1, 1, "Decision tree regressor"),
    e("SVM", "Machine Learning", "SVM Classifier", 1, 1, "Support vector machine classifier"),
    e("SVMRegressor", "Machine Learning", "SVM Regressor", 1, 1, "Support vector machine regressor"),
    e("KNN", "Machine Learning", "KNN Classifier", 1, 1, "K-nearest neighbors classifier"),
    e("RandomForest", "Machine Learning", "Random Forest", 1, 1, "Random forest ensemble"),
    e("GradientBoosting", "Machine Learning", "Gradient Boosting", 1, 1, "Gradient boosting ensemble"),
    e("NaiveBayes", "Machine Learning", "Naive Bayes", 1, 1, "Naive Bayes classifier"),
    e("LinearRegression", "Machine Learning", "Linear Regression", 1, 1, "Linear regression model"),
    e("LogisticRegression", "Machine Learning", "Logistic Regression", 1, 1, "Logistic regression classifier"),
    e("KMeans", "Machine Learning", "K-Means Clustering", 1, 1, "K-means clusterer"),
    e("PCA", "Machine Learning", "PCA", 1, 1, "Principal component analysis"),
    e("Normalization", "Machine Learning", "Feature Normalization", 1, 1, "Normalize feature vector"),
    // ──── Utility ────
    e("Reference", "Utility", "Library Reference", 1, 1, "Reference to library block"),
    e("SimpleAnnotation", "Utility", "Text Annotation", 0, 0, "Free text annotation (non-block)"),
    e("ConfigurationBlock", "Utility", "Configuration", 0, 0, "Model configuration block"),
    e("ModelInfo", "Utility", "Model Info", 0, 0, "Display model information"),
    e("SignalLabel", "Utility", "Signal Label", 1, 1, "Label a signal"),
    e("NoteBlock", "Utility", "Note Block", 0, 0, "Add note to diagram"),
    e("BoundaryDiagram", "Utility", "Boundary Diagram", 0, 0, "Boundary diagram block"),
    e("RequirementBlock", "Utility", "Requirement", 0, 0, "Link to requirement"),
    // ──── Optimization ────
    e("QPSolver", "Optimization", "QP Solver", 2, 1, "Quadratic programming solver"),
    e("LPSolver", "Optimization", "LP Solver", 2, 1, "Linear programming solver"),
    e("NonlinearSolver", "Optimization", "Nonlinear Solver", 1, 1, "Nonlinear equation solver"),
    e("GeneticAlgorithm", "Optimization", "Genetic Algorithm", 1, 1, "Genetic optimization"),
    e("ParticleSwarm", "Optimization", "Particle Swarm", 1, 1, "Particle swarm optimization"),
    e("SimulatedAnnealing", "Optimization", "Simulated Annealing", 1, 1, "Simulated annealing optimizer"),
    e("GradientDescent", "Optimization", "Gradient Descent", 1, 1, "Gradient descent optimizer"),
    e("NewtonRaphson", "Optimization", "Newton-Raphson", 1, 1, "Newton-Raphson root finder"),
    // ──── Fixed-Point ────
    e("FixedPointConvert", "Fixed-Point", "Fixed-Point Conversion", 1, 1, "Convert to/from fixed-point"),
    e("FixedPointGain", "Fixed-Point", "Fixed-Point Gain", 1, 1, "Fixed-point gain"),
    e("FixedPointSum", "Fixed-Point", "Fixed-Point Sum", 2, 1, "Fixed-point addition"),
    e("FixedPointProduct", "Fixed-Point", "Fixed-Point Product", 2, 1, "Fixed-point multiplication"),
    e("FixedPointLookup", "Fixed-Point", "Fixed-Point Lookup Table", 1, 1, "Fixed-point lookup table"),
    e("FixedPointRelay", "Fixed-Point", "Fixed-Point Relay", 1, 1, "Fixed-point relay"),
    e("FixedPointSaturation", "Fixed-Point", "Fixed-Point Saturation", 1, 1, "Fixed-point saturation"),
    e("FixedPointSubtract", "Fixed-Point", "Fixed-Point Subtract", 2, 1, "Fixed-point subtraction"),
    e("FixedPointDivide", "Fixed-Point", "Fixed-Point Divide", 2, 1, "Fixed-point division"),
    e("FixedPointAbs", "Fixed-Point", "Fixed-Point Abs", 1, 1, "Fixed-point absolute value"),
    // ──── Hardware I/O ────
    e("AnalogInput", "Hardware I/O", "Analog Input", 0, 1, "Read analog input pin"),
    e("AnalogOutput", "Hardware I/O", "Analog Output", 1, 0, "Write analog output pin"),
    e("DigitalInput", "Hardware I/O", "Digital Input", 0, 1, "Read digital input pin"),
    e("DigitalOutput", "Hardware I/O", "Digital Output", 1, 0, "Write digital output pin"),
    e("PWMOutput", "Hardware I/O", "PWM Output", 1, 0, "Generate PWM output"),
    e("PWMInput", "Hardware I/O", "PWM Input", 0, 1, "Read PWM duty cycle"),
    e("I2CRead", "Hardware I/O", "I2C Read", 0, 1, "Read from I2C bus"),
    e("I2CWrite", "Hardware I/O", "I2C Write", 1, 0, "Write to I2C bus"),
    e("SPIRead", "Hardware I/O", "SPI Read", 0, 1, "Read from SPI bus"),
    e("SPIWrite", "Hardware I/O", "SPI Write", 1, 0, "Write to SPI bus"),
    e("EncoderRead", "Hardware I/O", "Encoder Read", 0, 1, "Read quadrature encoder"),
    e("CounterInput", "Hardware I/O", "Counter Input", 0, 1, "Count pulses on input"),
    e("GPIORead", "Hardware I/O", "GPIO Read", 0, 1, "General purpose I/O read"),
    e("GPIOWrite", "Hardware I/O", "GPIO Write", 1, 0, "General purpose I/O write"),
    e("InterruptCallback", "Hardware I/O", "External Interrupt", 0, 1, "Trigger on external interrupt"),
    e("DACOutput", "Hardware I/O", "DAC Output", 1, 0, "Digital-to-analog output"),
    e("ADCInput", "Hardware I/O", "ADC Input", 0, 1, "Analog-to-digital input"),
    // ──── Special Math ────
    e("Gamma", "Special Math", "Gamma Function", 1, 1, "Gamma function Γ(x)"),
    e("Beta", "Special Math", "Beta Function", 2, 1, "Beta function B(a,b)"),
    e("Bessel", "Special Math", "Bessel Function", 1, 1, "Bessel function of first kind"),
    e("Erf", "Special Math", "Error Function", 1, 1, "Error function erf(x)"),
    e("Erfc", "Special Math", "Complementary Error", 1, 1, "Complementary error function erfc(x)"),
    e("Factorial", "Special Math", "Factorial", 1, 1, "Factorial n!"),
    e("Binomial", "Special Math", "Binomial Coefficient", 2, 1, "Binomial coefficient C(n,k)"),
    e("Signum", "Special Math", "Signum", 1, 1, "Sign function (-1, 0, +1)"),
    e("Sinc", "Special Math", "Sinc", 1, 1, "Sinc function sin(x)/x"),
    e("HyperbolicTrig", "Special Math", "Hyperbolic Trig", 1, 1, "sinh, cosh, tanh, etc."),
    e("InverseHyperbolic", "Special Math", "Inverse Hyperbolic", 1, 1, "asinh, acosh, atanh"),
    e("InverseTrig", "Special Math", "Inverse Trig", 1, 1, "asin, acos, atan"),
    e("Atan2", "Special Math", "atan2", 2, 1, "Four-quadrant inverse tangent"),
    e("ComplexConjugate", "Special Math", "Complex Conjugate", 1, 1, "Conjugate of complex number"),
    e("ComplexMagnitude", "Special Math", "Complex Magnitude", 1, 1, "Magnitude of complex number"),
    e("ComplexAngle", "Special Math", "Complex Angle", 1, 1, "Phase angle of complex number"),
    e("Floor", "Special Math", "Floor", 1, 1, "Floor function"),
    e("Ceil", "Special Math", "Ceil", 1, 1, "Ceiling function"),
    e("Fix", "Special Math", "Fix (Truncate)", 1, 1, "Truncate toward zero"),
    e("Rem", "Special Math", "Remainder", 2, 1, "Remainder after division"),
    // ──── Simulation Control ────
    e("InitCondition", "Simulation Control", "Initial Condition", 1, 1, "Set initial condition for signal"),
    e("SimulationPace", "Simulation Control", "Simulation Pace", 0, 0, "Control simulation speed"),
    e("StopBlock", "Simulation Control", "Stop", 1, 0, "Stop simulation on condition"),
    e("Assert", "Simulation Control", "Assert", 1, 0, "Assert runtime condition"),
    e("MessageBlock", "Simulation Control", "Message", 1, 1, "Send/receive simulation messages"),
    e("EntityGenerator", "Simulation Control", "Entity Generator", 0, 1, "Generate discrete entities"),
    e("EntityServer", "Simulation Control", "Entity Server", 1, 1, "Serve discrete entities"),
    e("EntityTerminator", "Simulation Control", "Entity Terminator", 1, 0, "Terminate entities"),
    e("Queue", "Simulation Control", "Queue", 1, 1, "FIFO/LIFO entity queue"),
    e("ServerBlock", "Simulation Control", "Server", 1, 1, "Service processing server"),
    // ──── String Operations ────
    e("StringConstant", "String Operations", "String Constant", 0, 1, "Output constant string"),
    e("StringConcat", "String Operations", "String Concatenation", 2, 1, "Concatenate strings"),
    e("StringLength", "String Operations", "String Length", 1, 1, "Length of string"),
    e("StringCompare", "String Operations", "String Compare", 2, 1, "Compare two strings"),
    e("StringToNum", "String Operations", "String to Number", 1, 1, "Convert string to number"),
    e("NumToString", "String Operations", "Number to String", 1, 1, "Convert number to string"),
    e("StringScan", "String Operations", "String Scan", 1, 1, "Scan/parse string"),
    e("StringCompose", "String Operations", "String Compose", 2, 1, "Format string with values"),
    // ──── Advanced ────
    e("AlgebraicLoop", "Advanced", "Algebraic Loop Solver", 1, 1, "Solve algebraic loops"),
    e("StateWriter", "Advanced", "State Writer", 1, 0, "Write to block states"),
    e("StateReader", "Advanced", "State Reader", 0, 1, "Read block states"),
    e("RuntimeParameter", "Advanced", "Runtime Parameter", 0, 1, "Tunable runtime parameter"),
    e("DesignVerifier", "Advanced", "Design Verifier", 1, 0, "Design verification block"),
    e("RequirementLink", "Advanced", "Requirement Link", 0, 0, "Link to requirement"),
    e("CoverageMarker", "Advanced", "Coverage Marker", 0, 0, "Mark coverage point"),
    // ──── Aerospace ────
    e("AeroFlatEarth", "Aerospace", "Flat Earth", 3, 3, "Flat earth equations of motion"),
    e("AeroWGS84", "Aerospace", "WGS84 Gravity", 1, 1, "WGS84 gravity model"),
    e("AeroISA", "Aerospace", "ISA Atmosphere", 1, 4, "International standard atmosphere"),
    e("AeroWindShear", "Aerospace", "Wind Shear", 3, 1, "Wind shear model"),
    e("AeroAerodynamics", "Aerospace", "Aerodynamic Forces", 6, 3, "Compute aerodynamic forces and moments"),
    e("AeroQuaternion", "Aerospace", "Quaternion", 2, 1, "Quaternion math operations"),
    e("AeroDirectionCosine", "Aerospace", "Direction Cosine", 1, 1, "Direction cosine matrix"),
    e("AeroEulerAngles", "Aerospace", "Euler Angles", 1, 3, "Convert to/from Euler angles"),
    e("AeroIdealAccel", "Aerospace", "Ideal Accelerometer", 3, 1, "Ideal accelerometer sensor"),
    e("AeroIdealGyro", "Aerospace", "Ideal Gyroscope", 2, 1, "Ideal gyroscope sensor"),
    e("AeroSixDOF", "Aerospace", "6DOF (Euler)", 3, 4, "Six degrees of freedom (Euler angles)"),
    e("AeroSixDOFQuat", "Aerospace", "6DOF (Quaternion)", 3, 4, "Six degrees of freedom (quaternion)"),
    e("AeroLLAtoECEF", "Aerospace", "LLA to ECEF", 1, 1, "Geodetic to ECEF coordinates"),
    e("AeroECEFtoLLA", "Aerospace", "ECEF to LLA", 1, 1, "ECEF to geodetic coordinates"),
    // ──── Phased Array ────
    e("PhasedULA", "Phased Array", "ULA", 1, 1, "Uniform linear array"),
    e("PhasedURA", "Phased Array", "URA", 1, 1, "Uniform rectangular array"),
    e("PhasedSteeringVector", "Phased Array", "Steering Vector", 1, 1, "Array steering vector"),
    e("PhasedBeamformer", "Phased Array", "Beamformer", 1, 1, "Beamforming"),
    e("PhasedMatchedFilter", "Phased Array", "Matched Filter", 1, 1, "Matched filtering"),
    e("PhasedCFAR", "Phased Array", "CFAR Detector", 1, 1, "CFAR detection"),
    e("PhasedWaveform", "Phased Array", "Waveform Generator", 0, 1, "Radar waveform generation"),
    // ──── Computer Vision ────
    e("CVImageRead", "Computer Vision", "Image Source", 0, 1, "Read image data"),
    e("CVImageDisplay", "Computer Vision", "Image Display", 1, 0, "Display image"),
    e("CVColorConvert", "Computer Vision", "Color Space Conversion", 1, 1, "Convert color spaces (RGB/HSV/YCbCr)"),
    e("CVEdgeDetect", "Computer Vision", "Edge Detection", 1, 1, "Detect edges (Sobel/Canny)"),
    e("CVMedianFilter", "Computer Vision", "Median Filter", 1, 1, "Median image filter"),
    e("CVGaussianFilter", "Computer Vision", "Gaussian Filter", 1, 1, "Gaussian image blur"),
    e("CVMorphology", "Computer Vision", "Morphological Op", 1, 1, "Morphological operation (dilate/erode)"),
    e("CVTemplate", "Computer Vision", "Template Matching", 2, 1, "Template matching"),
    e("CVOpticalFlow", "Computer Vision", "Optical Flow", 1, 1, "Optical flow estimation"),
    e("CVHoughLines", "Computer Vision", "Hough Lines", 1, 1, "Hough line transform"),
    // ──── Deep Learning ────
    e("DLConv2D", "Deep Learning", "2-D Convolution", 1, 1, "2-D convolutional layer"),
    e("DLMaxPool", "Deep Learning", "Max Pooling", 1, 1, "Max pooling layer"),
    e("DLAvgPool", "Deep Learning", "Average Pooling", 1, 1, "Average pooling layer"),
    e("DLFullyConnected", "Deep Learning", "Fully Connected", 1, 1, "Fully connected (dense) layer"),
    e("DLReLU", "Deep Learning", "ReLU Layer", 1, 1, "Rectified linear unit activation"),
    e("DLSoftmax", "Deep Learning", "Softmax Layer", 1, 1, "Softmax normalization"),
    e("DLBatchNorm", "Deep Learning", "Batch Normalization", 1, 1, "Batch normalization layer"),
    e("DLDropout", "Deep Learning", "Dropout Layer", 1, 1, "Dropout regularization layer"),
    e("DLLSTM", "Deep Learning", "LSTM Layer", 1, 1, "Long short-term memory layer"),
    e("DLGRU", "Deep Learning", "GRU Layer", 1, 1, "Gated recurrent unit layer"),
    // ──── Navigation ────
    e("NavINS", "Navigation", "INS", 3, 3, "Inertial navigation system"),
    e("NavGPS", "Navigation", "GPS Receiver", 1, 3, "GPS receiver model"),
    e("NavIMU", "Navigation", "IMU", 3, 3, "Inertial measurement unit"),
    e("NavKalman", "Navigation", "Navigation Kalman", 3, 3, "Navigation Kalman filter"),
    e("NavMagnetometer", "Navigation", "Magnetometer", 1, 1, "Magnetometer sensor model"),
    e("NavBarometer", "Navigation", "Barometer", 1, 1, "Barometric altimeter"),
    // ──── RF ────
    e("RFAmplifier", "RF", "RF Amplifier", 1, 1, "RF amplifier model"),
    e("RFMixer", "RF", "RF Mixer", 2, 1, "RF mixer"),
    e("RFFilter", "RF", "RF Filter", 1, 1, "RF bandpass/lowpass filter"),
    e("RFOscillator", "RF", "Oscillator", 0, 1, "RF oscillator"),
    e("RFPLL", "RF", "Phase-Locked Loop", 1, 1, "Phase-locked loop"),
    e("RFVCO", "RF", "VCO", 1, 1, "Voltage-controlled oscillator"),
    e("RFSParameter", "RF", "S-Parameter", 1, 1, "S-parameter block"),
    // ──── Verification ────
    e("TestInput", "Verification", "Test Input", 0, 1, "Test harness input signal"),
    e("TestOutput", "Verification", "Test Assessment", 1, 0, "Test output assessment"),
    e("TestScenario", "Verification", "Test Scenario", 0, 1, "Test scenario definition"),
    e("TestProbe", "Verification", "Test Probe", 1, 1, "Test probe point"),
    e("TestAssumption", "Verification", "Test Assumption", 1, 0, "Assumption for design verifier"),
    e("TestObjective", "Verification", "Test Objective", 1, 0, "Objective for design verifier"),
    // ──── Thermal ────
    e("ThermalCapacitor", "Thermal", "Thermal Capacitor", 1, 1, "Thermal capacitance element"),
    e("ThermalConduction", "Thermal", "Conductive Heat", 2, 1, "Conductive heat transfer"),
    e("ThermalConvection", "Thermal", "Convective Heat", 2, 1, "Convective heat transfer"),
    e("ThermalRadiation", "Thermal", "Radiative Heat", 2, 1, "Radiative heat transfer"),
    e("ThermalSensor", "Thermal", "Temp Sensor", 1, 1, "Temperature sensor"),
    e("ThermalSource", "Thermal", "Heat Source", 0, 1, "Ideal heat flow source"),
    e("ThermalRef", "Thermal", "Thermal Reference", 0, 1, "Thermal reference (ambient)"),
    e("ThermalResistor", "Thermal", "Thermal Resistor", 2, 1, "Thermal resistance element"),
];
